# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='pub_date',
        ),
    ]
