# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170612_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(verbose_name='pub_date'),
        ),
    ]
